# Directories
databaseDirectory: Database
rawFastQDirectory: Data/Raw_FastQ
trimmedFastQDirectory: Data/FastP
nohumanDirectory: Data/NoHuman
metaphlanDirectory: Data/Metaphlan
singlemDirectory: Data/SingleM
multiQCDirectory: Reports/MultiQC
qcOutputDirectory: Reports/FastQC
metaspadesDirectory: Data/MetaSPAdes
humannDirectory: Data/HUMAnN
mlpDirectory: Data/MLP
logDirectory: logs
slurmLogDirectory: logs/slurm

# Flags
test_mode: false
download_sra: false
metaphlan: true
singlem: true
metaspades: false
mlp: false
humann: false 

# HPC
executor: slurm
default_resources: []
jobs: 20