# Directories
databaseDirectory: Database
rawFastQDirectory: Data/Raw_FastQ
trimmedFastQDirectory: Data/FastP
nohumanDirectory: Data/NoHuman
metaphlanDirectory: Data/Metaphlan
singlemDirectory: Data/SingleM
kraken2Directory: Data/Kraken2
multiQCDirectory: Reports/MultiQC
qcOutputDirectory: Reports/FastQC
metaspadesDirectory: Data/MetaSPAdes
humannDirectory: Data/HUMAnN
mlpDirectory: Data/MLP
rgiDirectory: Data/RGI
antismashDirectory: Data/AntiSMASH
logDirectory: logs
slurmLogDirectory: logs/slurm

# Flags
test_mode: false
download_sra: false
metaphlan: true
singlem: true
kraken2: false
metaspades: false
mlp: false
humann: false 
rgi: false
antismash: false

# HPC
executor: slurm
default_resources: []
jobs: 20