# Directories
databaseDirectory: Database
rawFastQDirectory: Data/Raw_FastQ
trimmedFastQDirectory: Data/FastP
nohumanDirectory: Data/NoHuman
metaphlanDirectory: Data/Metaphlan
singlemDirectory: Data/SingleM
multiQCDirectory: Reports/MultiQC
qcOutputDirectory: Reports/FastQC
logDirectory: logs
slurmLogDirectory": logs/slurm

# Flags
metaphlan: true
singlem: true

# HPC
executor: slurm
default_resources: []
jobs: 20