databaseDirectory: Database
rawFastQDirectory: Data/Raw_FastQ
trimmedFastQDirectory: Data/FastP
nohumanDirectory: Data/NoHuman
metaphlanDirectory: Data/Metaphlan
singlemDirectory: Data/SingleM
multiQCDirectory: Reports/MultiQC
qcOutputDirectory: Reports/FastQC
logDirectory: logs
slurmLogDirectory": logs/slurm
run_nohuman: true
run_metaphlan: true
run_singlem: true

executor: slurm
default_resources: []
jobs: 20